# Thanks to RasCas for the translation. Danke RasCas.
# This version is only partially translated because I made major changes to the file right after RasCas translated it.
# I started to translate commands as an example.
# The full version of this config has helpful comments describing the options. 
# If your config file has been migrated from an older version, it may only include these comments.
configuration:
  # Leave the version alone, it's the config version, not the plugin version.
  config-version: 1
  # Detect people using /time [x] and cancel any active shift on their world. 
  detect-time: true
  # Convert &[0-9a-f] as color codes. (&0, &1, ...) Matches the minecraft code #s: http://www.minecraftwiki.net/wiki/Formatting_codes
  colorize-strings: false
  classic:
    on: false # turn on classic(more frequent) job scheduling
    poll-rate: 100 # How often to check the server time (in approximate ticks) when classic is on.
strings:
# Customizable strings and destinations.
# Valid destinations are 'server-announce', 'world-announce', and 'player'
  shift:
    string: 'Die Zeit auf der Welt: [%world] hat sich plötzlich verändert.'
    destination: server-announce
  cancel:
    string: 'Die Zeit auf Welt: [%world] scheint wieder normal zu verlaufen.'
    destination: server-announce
  startup:
    shift:
      string: 'Die Welt: [%world] ist nach einem Neustart in einer %setting - Zeitschleife
        gefangen'
      destination: player
    cancel:
      string: 'Welt: [%world] wird nach dem Neustart nicht mehr in einer Zeitschleife
        gefangen sein'
      destination: player
  errors:
  errors:
    error-logging: true
    dne: 'Die Welt: [%world] existiert nicht!'
    shift-permission: 'Um dies zu tun benötigst Du das Zugriffsrecht: timeshift.shift'
    startup-permission: 'Um dies zu tun benötigst Du das Zugriffsrecht: timeshift.startup'
    console-specify: 'Du musst eine Welt angeben, wenn Du die Console benutzt.'
    no-perm: 'Du hast leider keinen Zugriff auf die TimeShift Kommandos.'
    stop-permission: 'You need timeshift.cancel permission.'
  help:
    console: 'Anwendung: shift <Tag | Nacht | stop | sunrise | sunset | setrise> <world(s)>'
    shift-only: 'Anwendung: /shift <Tag | Nacht | stop | sunrise | sunset | setrise>'
    startup-only: 'Anwendung: /shift startup <Tag | Nacht | stop | sunrise | sunset
      | setrise> -- sets startup and /reload behavior only'
    shift-startup: 'Anwendung: /shift <Tag | Nacht | stop | sunrise | sunset | setrise
      | startup [option]>'
commands:
# A basic definition. You can add your own, or adjust the ranges, but these should provide some nice defaults.
  Tag:
  # Synonyms. Capitalization doesn't matter.
    aliases:
      - day
    # Most common type, if you forget this, it'll be assumed, but you'll get a notice about it on startup.
    type: loop
    times:
    # Minecraft time uses a 24000 tick clock, with approximately 20 ticks/second occurring under optimum conditions.
    # The times below may give you some hint as to when 
      - 450 # Time to loop from
      - 11449 # Time to loop to
  Nacht:
    aliases:
      - night
    type: loop
    times:
      - 14100
      - 21899
  sunrise:
    aliases:
      - rise
    type: loop
    times:
      - 21900
      - 24000
      - 0
      - 550
  sunset:
    aliases:
      - set
    type: loop
    times:
      - 11550
      - 14149
# This is a little different: now we have two periods defined instead of one. You can define as many periods as you want. They run sequentially, and will loop.
  setrise:
    aliases:
      - riseset
    # It's still a loop though, really common, like I said.
    type: loop
    times:
    # These are the sunset settings from above.
      - 11550
      - 14149
    # These are the sunrise settings from above.
      - 21900
      - 24000
      - 0
      - 550
      # They were both pairs. Odd numbers will cause your setting to be rejected
# Another special one! You'll only ever have one of these...
  startup:
    aliases:
      - start
    # Ooh, look there! That's it! A modifier for "Startup" behavior.
    type: startup
  stop:
    type: stop