name: TimeShift
main: tazzernator.cjc.timeshift.TimeShift
version: 2.2
website: http://forums.bukkit.org/posts/14655/
author: Tazzernator and cjc (TimeShift), and feverdream (open source time logic)
database: true
description: >
             Allows the time to be looped on demand, or at startup, for each world.
             This plugin uses the optional Permissions nodes timeshift.startup, timeshift.shift, and timeshift.cancel
commands:
  shift:
    description: Changes time behavior.
    usage: |
           /<command> - displays permission specific help.
           /<command> day - loops day.
           /<command> night - loops night.
           /<command> stop - stops looping.
           /<command> sunrise - loops sunrise.
           /<command> sunset - loops sunset.
           /<command> setrise - loops sunrise and sunset.
           /<command> startup [state] - sets world startup behavior.
           /time [anything] - cancels active shifts.
           Example: /<command> startup day - sets world to loop day on        startup (or /reload, which you shouldn't use).
           Example: /<command> night - sets world to loop night.
permissions:
  timeshift.shift:
    description: Allows the player to loop time and cancel loops
  timeshift.cancel:
    description: Allows the player to cancel loops only via '/time [x]' commands
  timeshift.startup:
    description: Allows the player to change the startup behavior
  timeshift.*:
    description: Gives all permissions for TimeShift
    default: op
    children:
      timeshift.shift: true
      timeshift.cancel: true
      timeshift.startup: true